name: Bench
on: push
jobs:
  test:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623 # v1.1.3
        with:
          deno-version: v1.x
      - run: deno task bench
